name: superstore-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - pip:
    - mlxtend
    - jupyter
    - notebook
